#ifndef MSIPCHEADER
#define MSIPCHEADER

///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1997-2001 Morgan Stanley Dean Witter & Co. All rights reserved. 
// See .../src/LICENSE for terms of distribution
//
//
///////////////////////////////////////////////////////////////////////////////


#include <MSIPC/MSTimer.H>
#include <MSIPC/MSChannel.H>
#include <MSIPC/MSProtocol.H> 
#include <MSIPC/MSConnection.H> 
#include <MSIPC/MSListener.H>

#endif




