#ifndef __LibtUtilities_H
#define __LibtUtilities_H

///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1997-2001 Morgan Stanley Dean Witter & Co. All rights reserved.
// See .../src/LICENSE for terms of distribution.
//
//
///////////////////////////////////////////////////////////////////////////////

extern A tp_a_object(char *recbuf, A fields);
extern C *libtMakeClasses(A clss);
extern A libtMakeFields(A clss);

#endif
