#ifndef AGIFHEADER
#define AGIFHEADER

///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1997-2001 Morgan Stanley Dean Witter & Co. All rights reserved.
// See .../src/LICENSE for terms of distribution.
//
//
///////////////////////////////////////////////////////////////////////////////

#include <MSGUI/MSColorManager.H>
#include <a/fncdcls.h>
#include <AplusGUI/AplusDisplayServer.H>

#endif // AGIFHEADER
