#ifndef AGIFGraphHEADER
#define AGIFGraphHEADER

///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1997-2001 Morgan Stanley Dean Witter & Co. All rights reserved.
// See .../src/LICENSE for terms of distribution.
//
//
///////////////////////////////////////////////////////////////////////////////

#include <AplusGUI/AplusGraph.H>
#include <AplusGUI/AplusTrace.H>

#endif //AGIFGraphHEADER

